"""
confirm_gate.py — AI OS Confirmation Engine

Implements: Detect → Analyze → Explain → Suggest → Execute (if approved)

Critical rule: "Execute" only happens if the approval came from a
HMAC-verified HUMAN token — not from AI-generated text, not from
content the AI read from a file or webpage.

This module sits between the AI planner and the executor.
The AI planner proposes actions. This module decides whether
they need confirmation, what risk level they are, and whether
the user's "yes" was genuinely from the user.
"""

import asyncio
import json
import logging
import os
import time
from dataclasses import dataclass
from enum import Enum, auto
from pathlib import Path
from typing import Callable

log = logging.getLogger("confirm-gate")


# ── Risk classification ────────────────────────────────────────────────────────

class RiskLevel(Enum):
    AUTO   = auto()   # execute silently (L0–L1, reversible, no side effects)
    NOTIFY = auto()   # show notification, auto-proceed after 5s unless cancelled
    CONFIRM = auto()  # explicit user confirmation required
    BLOCK   = auto()  # hard block — never execute regardless of confirmation


@dataclass
class ActionProposal:
    action_type:   str         # "launch_app", "type_text", "run_command", etc.
    params:        dict
    description:   str         # human-readable description generated by AI
    risk_level:    RiskLevel
    reversible:    bool
    simulation_result: dict | None = None


# ── Risk classifier ─────────────────────────────────────────────────────────

# Patterns for HARD BLOCK — never execute, no confirmation overrides this
BLOCK_PATTERNS = [
    lambda p: _path_dangerous(p.get("command", "")),
    lambda p: "rm -rf /" in p.get("command", ""),
    lambda p: "/etc/shadow" in str(p),
    lambda p: "/etc/sudoers" in str(p),
    lambda p: p.get("tool") == "run_command" and "curl" in p.get("command","")
              and "| bash" in p.get("command",""),  # classic RCE pattern
]

# Patterns requiring CONFIRM (user must actively say yes)
CONFIRM_PATTERNS = [
    lambda p, a: a == "run_command",
    lambda p, a: "delete" in str(p).lower() or "remove" in str(p).lower(),
    lambda p, a: "payment" in str(p).lower() or "order" in str(p).lower()
                 or "buy" in str(p).lower() or "purchase" in str(p).lower(),
    lambda p, a: a == "system_config_change",
    lambda p, a: a == "install_package",
    lambda p, a: _writes_to_system_path(str(p)),
]

# Patterns for NOTIFY (shown but auto-proceed)
NOTIFY_PATTERNS = [
    lambda p, a: a == "open_url",
    lambda p, a: a == "launch_app" and p.get("app") in ("firefox", "chromium"),
]


def _path_dangerous(cmd: str) -> bool:
    dangerous_paths = {"/boot", "/lib", "/lib64", "/usr/lib", "/bin", "/sbin",
                       "/usr/bin", "/usr/sbin", "/etc/systemd"}
    return any(dp in cmd for dp in dangerous_paths)


def _writes_to_system_path(param_str: str) -> bool:
    system_prefixes = ("/etc/", "/usr/", "/lib/", "/bin/", "/sbin/", "/boot/")
    return any(p in param_str for p in system_prefixes)


def classify_risk(proposal: ActionProposal) -> RiskLevel:
    p, a = proposal.params, proposal.action_type

    # Hard block first — check before anything else
    if any(check(p) for check in BLOCK_PATTERNS):
        return RiskLevel.BLOCK

    # Simulation result overrides if risk_score is high
    if proposal.simulation_result:
        score = proposal.simulation_result.get("risk_score", 0)
        if score > 0.85:
            return RiskLevel.BLOCK
        if score > 0.5:
            return RiskLevel.CONFIRM

    # Pattern-based
    if any(check(p, a) for check in CONFIRM_PATTERNS):
        return RiskLevel.CONFIRM
    if any(check(p, a) for check in NOTIFY_PATTERNS):
        return RiskLevel.NOTIFY

    return RiskLevel.AUTO


# ── Human token verification ─────────────────────────────────────────────────

def _verify_human_token(token_data: dict) -> bool:
    """
    Import the verifier from input_tagger.
    Falls back to False if tagger is not running (safe default).
    """
    try:
        from input_tagger import HumanTokenVerifier
        return HumanTokenVerifier().verify(token_data)
    except Exception as e:
        log.error(f"[gate] Token verification failed: {e}")
        return False  # fail closed


# ── Confirmation UI bridge ────────────────────────────────────────────────────

class ConfirmationUI:
    """
    Sends a confirmation request to the UI frontend (chat sidebar).
    Waits for a HMAC-verified response from the input tagger.
    Timeout defaults to 60 seconds — after which the action is CANCELLED.
    """

    UI_SOCKET = "/run/ai-os/confirm-ui.sock"

    async def ask(self, proposal: ActionProposal,
                  timeout: float = 60.0) -> tuple[bool, dict | None]:
        """
        Returns (approved: bool, token: dict | None).
        token is the HMAC-verified human input event, if available.
        """
        msg = {
            "type":        "confirm_request",
            "action":      proposal.action_type,
            "description": proposal.description,
            "risk":        proposal.risk_level.name,
            "reversible":  proposal.reversible,
            "params_summary": _safe_params_summary(proposal.params),
        }

        if not Path(self.UI_SOCKET).exists():
            # No UI connected — fall back to terminal prompt
            return await self._terminal_fallback(msg, timeout)

        try:
            reader, writer = await asyncio.open_unix_connection(self.UI_SOCKET)
            writer.write((json.dumps(msg) + "\n").encode())
            await writer.drain()

            resp_raw = await asyncio.wait_for(reader.readline(), timeout=timeout)
            writer.close()
            resp = json.loads(resp_raw.decode())

            approved = resp.get("approved", False)
            token    = resp.get("human_token")

            if approved and token and not _verify_human_token(token):
                log.warning("[gate] Approval received but HMAC verification FAILED")
                return False, None

            return approved, token

        except asyncio.TimeoutError:
            log.info("[gate] Confirmation timed out — action CANCELLED")
            return False, None
        except Exception as e:
            log.error(f"[gate] UI socket error: {e}")
            return False, None

    async def notify(self, message: str):
        """Non-blocking notification — no confirmation needed."""
        msg = {"type": "notify", "message": message}
        if Path(self.UI_SOCKET).exists():
            try:
                _, writer = await asyncio.open_unix_connection(self.UI_SOCKET)
                writer.write((json.dumps(msg) + "\n").encode())
                await writer.drain()
                writer.close()
            except Exception:
                pass
        else:
            print(f"[AI OS] {message}")

    async def _terminal_fallback(self, msg: dict,
                                  timeout: float) -> tuple[bool, None]:
        """When running headless — prompt via terminal."""
        print(f"\n[AI OS — Confirmation Required]")
        print(f"Action : {msg['action']}")
        print(f"Details: {msg['description']}")
        print(f"Risk   : {msg['risk']}")

        try:
            loop = asyncio.get_event_loop()
            answer = await asyncio.wait_for(
                loop.run_in_executor(None, input, "Approve? [y/N]: "),
                timeout=timeout,
            )
            # Terminal fallback cannot verify HMAC — approved but unverified
            return answer.strip().lower() in ("y", "yes"), None
        except asyncio.TimeoutError:
            return False, None


def _safe_params_summary(params: dict) -> dict:
    """Strip secrets/long values for UI display."""
    summary = {}
    for k, v in params.items():
        sv = str(v)
        if len(sv) > 120:
            sv = sv[:120] + "…"
        if any(secret in k.lower() for secret in ("password","token","key","secret")):
            sv = "***"
        summary[k] = sv
    return summary


# ── Main gate ─────────────────────────────────────────────────────────────────

class ConfirmationGate:
    """
    The single choke point between the AI planner and the executor.
    Every proposed action passes through here.
    """

    def __init__(self, on_execute: Callable, on_block: Callable | None = None):
        self.ui = ConfirmationUI()
        self._on_execute = on_execute
        self._on_block   = on_block or (lambda p, r: None)
        self._action_log: list[dict] = []

    async def process(self, proposal: ActionProposal) -> dict:
        """
        Main entry point. Returns execution result or refusal.
        """
        # Classify risk (this may update proposal.risk_level)
        risk = classify_risk(proposal)
        proposal.risk_level = risk

        self._log(proposal, "proposed", risk)

        # ── Hard block ──────────────────────────────────────────────────────
        if risk == RiskLevel.BLOCK:
            msg = (f"Action '{proposal.action_type}' was blocked by the safety "
                   f"engine. Reason: matched a hard-block pattern.")
            log.warning(f"[gate] BLOCKED: {proposal.action_type}")
            await self.ui.notify(msg)
            self._on_block(proposal, risk)
            self._log(proposal, "blocked", risk)
            return {"ok": False, "blocked": True, "reason": msg}

        # ── Silent execute ──────────────────────────────────────────────────
        if risk == RiskLevel.AUTO:
            result = await self._on_execute(proposal)
            self._log(proposal, "executed_auto", risk, result)
            return result

        # ── Notify (5s cancel window) ───────────────────────────────────────
        if risk == RiskLevel.NOTIFY:
            await self.ui.notify(
                f"AI is about to: {proposal.description} (cancel within 5s)"
            )
            try:
                await asyncio.sleep(5.0)
            except asyncio.CancelledError:
                self._log(proposal, "cancelled_notify", risk)
                return {"ok": False, "cancelled": True}
            result = await self._on_execute(proposal)
            self._log(proposal, "executed_notify", risk, result)
            return result

        # ── Explicit confirmation ───────────────────────────────────────────
        approved, token = await self.ui.ask(proposal)

        if not approved:
            self._log(proposal, "rejected_by_user", risk)
            return {"ok": False, "rejected": True,
                    "message": "User did not approve the action."}

        # Warn if confirmation was unverified (terminal fallback, no HMAC)
        if token is None:
            log.warning("[gate] Proceeding with unverified confirmation "
                        "(no HMAC token — terminal fallback mode)")

        result = await self._on_execute(proposal)
        self._log(proposal, "executed_confirmed", risk, result)
        return result

    def _log(self, proposal: ActionProposal, status: str,
             risk: RiskLevel, result: dict | None = None):
        entry = {
            "ts":      time.monotonic_ns(),
            "action":  proposal.action_type,
            "params":  _safe_params_summary(proposal.params),
            "risk":    risk.name,
            "status":  status,
        }
        if result:
            entry["result_ok"] = result.get("ok")
        self._action_log.append(entry)
        # In production: write to Merkle event log, not just in-memory list
        log.info(f"[gate] {status.upper()} | {proposal.action_type} | risk={risk.name}")
