#!/usr/bin/env bash
# 03_ai_brain.sh — AI Brain Setup
# Installs Ollama, pulls the right model for your RAM, installs Python deps.
# Detects RAM and chooses: phi3:mini (≤4GB) or mistral (≥6GB)

set -euo pipefail
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
info() { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }
step() { echo -e "\n${BLUE}▶${NC} $*"; }

[[ $EUID -ne 0 ]] && die "Run as root"

VENV="/opt/ai-os/venv"
[[ -d "$VENV" ]] || die "Run 01_base.sh first — venv not found at $VENV"

# ── 1. Detect RAM and pick model ──────────────────────────────────────────────
RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
RAM_GB=$(( RAM_KB / 1024 / 1024 ))

step "Detected RAM: ${RAM_GB} GB"

if (( RAM_GB <= 3 )); then
    MODEL="phi3:mini"
    CONFIG_FILE="config/low_ram.yaml"
    warn "3GB RAM — using phi3:mini (smallest model, limited reasoning)"
    warn "Consider adding swap: fallocate -l 4G /swapfile && mkswap /swapfile && swapon /swapfile"
elif (( RAM_GB <= 5 )); then
    MODEL="phi3:mini"
    CONFIG_FILE="config/low_ram.yaml"
    info "4-5GB RAM — using phi3:mini with low_ram config"
elif (( RAM_GB <= 10 )); then
    MODEL="mistral:7b-instruct-q4_K_M"
    CONFIG_FILE="config/default.yaml"
    info "6-10GB RAM — using mistral 7B Q4 (good balance)"
else
    MODEL="mistral:7b-instruct"
    CONFIG_FILE="config/default.yaml"
    info "10GB+ RAM — using mistral 7B full (best quality)"
fi

echo "Selected model: $MODEL"
echo "Config file:    $CONFIG_FILE"

# ── 2. Install Ollama ─────────────────────────────────────────────────────────
step "Installing Ollama"
if command -v ollama &>/dev/null; then
    warn "Ollama already installed — skipping"
else
    curl -fsSL https://ollama.com/install.sh | sh
    info "Ollama installed"
fi

# Run Ollama as a system service
systemctl enable --now ollama
sleep 3  # wait for socket to appear

# ── 3. Pull model ─────────────────────────────────────────────────────────────
step "Pulling model: $MODEL"
info "This may take a while (model download)..."
ollama pull "$MODEL"
info "Model ready"

# Also pull a code model if RAM allows
if (( RAM_GB >= 6 )); then
    step "Pulling code model: qwen2.5-coder:7b-instruct-q4_K_M"
    ollama pull qwen2.5-coder:7b-instruct-q4_K_M
    info "Code model ready"
fi

# ── 4. Python dependencies ────────────────────────────────────────────────────
step "Installing Python packages"

"$VENV/bin/pip" install --quiet \
    pyyaml \
    aiofiles \
    websockets \
    faster-whisper \
    evdev \
    psutil

# llama-cpp-python — try GPU build first, fall back to CPU
info "Installing llama-cpp-python (this takes a few minutes)"
if command -v nvidia-smi &>/dev/null; then
    info "GPU detected — building with CUDA support"
    CMAKE_ARGS="-DLLAMA_CUDA=on" \
    "$VENV/bin/pip" install llama-cpp-python --no-cache-dir || \
    "$VENV/bin/pip" install llama-cpp-python --no-cache-dir
else
    "$VENV/bin/pip" install llama-cpp-python --no-cache-dir
fi

# Ollama Python client (alternative to llama-cpp for runtime)
"$VENV/bin/pip" install --quiet ollama

chown -R ai-agent:ai-agent "$VENV"

# ── 5. Write active config ────────────────────────────────────────────────────
step "Writing active config"

AI_OS_DIR="/opt/ai-os"
mkdir -p "$AI_OS_DIR/config"

# Write the Ollama-compatible config variant
cat > "$AI_OS_DIR/config/active.yaml" << YAML
# Auto-generated by 03_ai_brain.sh
# RAM: ${RAM_GB}GB — Model: ${MODEL}

agent_socket: /run/ai-os/agent.sock

planner:
  backend: ollama              # use Ollama instead of llama-cpp directly
  ollama_model: ${MODEL}
  ollama_host: http://localhost:11434
  ctx_len: $(( RAM_GB <= 5 ? 2048 : 4096 ))
  temperature: 0.1

supervisor:
  rate_limit_actions: $(( RAM_GB <= 5 ? 6 : 10 ))
  rate_limit_window_sec: 30
  loop_exact_threshold: 3
  near_loop_threshold: 5
  session_budget: $(( RAM_GB <= 5 ? 100 : 200 ))
  consecutive_fail_threshold: 5

memory:
  db_path: /home/ai-agent/memory.db

snapshots:
  enabled: $(df -T / | awk 'NR==2{print $2}' | grep -q btrfs && echo true || echo false)
  snapper_config: root

voice:
  stt_model: $(( RAM_GB <= 4 ? "base" : "large-v3-turbo" ))
  stt_device: cpu
  stt_compute: int8
  language: en
  piper_model: en_US-amy-medium.onnx

logging:
  level: INFO
  file: /var/log/ai-os/agent.log
YAML

chown ai-agent:ai-agent "$AI_OS_DIR/config/active.yaml"
info "Config written to $AI_OS_DIR/config/active.yaml"

# ── 6. Test Ollama is working ─────────────────────────────────────────────────
step "Testing Ollama"
TEST_RESP=$(ollama run "$MODEL" "Reply with only the word: READY" 2>/dev/null | head -1)
if echo "$TEST_RESP" | grep -qi "ready"; then
    info "Ollama test passed — model responds correctly"
else
    warn "Ollama test response: '$TEST_RESP' — model may need a moment to load"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
info "AI brain setup complete"
echo "  Model:  $MODEL"
echo "  Config: $AI_OS_DIR/config/active.yaml"
echo "  Next:   bash 04_deploy.sh"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
