#!/usr/bin/env bash
# 04_deploy.sh — Deploy AI OS Layer
# Copies repo to /opt/ai-os, installs systemd units, starts everything.
# Run from the repo root: sudo bash install/04_deploy.sh

set -euo pipefail
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info() { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

[[ $EUID -ne 0 ]] && die "Run as root"

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST="/opt/ai-os"

info "Deploying from $REPO_DIR → $DEST"

# ── 1. Copy repo ──────────────────────────────────────────────────────────────
rsync -a --exclude='.git' --exclude='__pycache__' \
      --exclude='*.pyc' --exclude='models/' \
      "$REPO_DIR/" "$DEST/"

chown -R ai-agent:ai-agent "$DEST"
chmod -R o-rwx "$DEST"   # no world access
info "Repo deployed"

# ── 2. Link active config ─────────────────────────────────────────────────────
if [[ -f "$DEST/config/active.yaml" ]]; then
    info "Using active.yaml (generated by 03_ai_brain.sh)"
else
    warn "active.yaml not found — using default.yaml"
    cp "$DEST/config/default.yaml" "$DEST/config/active.yaml"
fi

# ── 3. Install system services ────────────────────────────────────────────────
info "Installing system services"

# ai-input-tagger (root)
cat > /etc/systemd/system/ai-input-tagger.service << 'SVC'
[Unit]
Description=AI OS Input Tagger
After=local-fs.target

[Service]
Type=simple
ExecStart=/opt/ai-os/venv/bin/python -m security.input_tagger
WorkingDirectory=/opt/ai-os
Environment=PYTHONPATH=/opt/ai-os
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
SVC

# ai-agent (UID 1001) — copy from repo
cp "$DEST/systemd/ai-agent.service" /etc/systemd/system/

# Patch ExecStart to use venv python + active config
sed -i "s|ExecStart=.*|ExecStart=/opt/ai-os/venv/bin/python -m core.agent_main --config /opt/ai-os/config/active.yaml|" \
    /etc/systemd/system/ai-agent.service

systemctl daemon-reload
systemctl enable ai-input-tagger
systemctl enable ai-agent
info "System services installed"

# ── 4. Install user services (for UID 1000) ───────────────────────────────────
info "Installing user services"
USER_SYSTEMD="/home/user/.config/systemd/user"
mkdir -p "$USER_SYSTEMD"

cp "$DEST/systemd/ai-dbus-proxy.service" "$USER_SYSTEMD/"
cp "$DEST/systemd/ai-ui-server.service"  "$USER_SYSTEMD/"
chown -R user:user "/home/user/.config/systemd"

# Enable as user services
sudo -u user XDG_RUNTIME_DIR="/run/user/1000" \
    systemctl --user daemon-reload 2>/dev/null || true
sudo -u user XDG_RUNTIME_DIR="/run/user/1000" \
    systemctl --user enable ai-dbus-proxy ai-ui-server 2>/dev/null || \
    warn "User services couldn't be enabled now — will activate on first login"

# ── 5. AppArmor profile ───────────────────────────────────────────────────────
if [[ -f "$DEST/apparmor/ai-agent" ]]; then
    cp "$DEST/apparmor/ai-agent" /etc/apparmor.d/ai-agent
    apparmor_parser -r /etc/apparmor.d/ai-agent && \
        info "AppArmor profile loaded" || \
        warn "AppArmor profile parse failed — check /etc/apparmor.d/ai-agent"
fi

# ── 6. Snapper sudo rules (allow ai-agent to create/rollback snapshots) ──────
info "Adding snapper sudo rules for ai-agent"
cat > /etc/sudoers.d/ai-agent-snapper << 'SUDO'
# Allow ai-agent to create and rollback Btrfs snapshots ONLY
ai-agent ALL=(root) NOPASSWD: /usr/bin/snapper create *
ai-agent ALL=(root) NOPASSWD: /usr/bin/snapper rollback *
ai-agent ALL=(root) NOPASSWD: /usr/bin/snapper list *
SUDO
chmod 0440 /etc/sudoers.d/ai-agent-snapper

# ── 7. Start services ─────────────────────────────────────────────────────────
info "Starting services"
systemctl start ai-input-tagger
sleep 1
systemctl start ai-agent
info "System services started"

# ── 8. Verify ─────────────────────────────────────────────────────────────────
sleep 2
echo ""
echo "Service status:"
for svc in ai-input-tagger ai-agent ollama; do
    STATUS=$(systemctl is-active "$svc" 2>/dev/null || echo "unknown")
    if [[ "$STATUS" == "active" ]]; then
        echo -e "  ${GREEN}✔${NC} $svc: $STATUS"
    else
        echo -e "  ${YELLOW}⚠${NC} $svc: $STATUS"
    fi
done

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
info "Deployment complete"
echo ""
echo "  Test the system:"
echo "  1. Reboot: sudo reboot"
echo "  2. Login as 'user' (auto-login should kick in)"
echo "  3. Open browser → http://localhost:8765/ui/index.html"
echo "  4. Type: 'open VS Code'"
echo ""
echo "  Check logs:"
echo "  sudo journalctl -u ai-agent -f"
echo "  sudo journalctl -u ai-input-tagger -f"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
